only logger.debug when options.debug is true
algoan/nestjs-components pull request #191
Opened 2021-03-16 07:35 UTC by samuelsweet

## Honor debug param in config

> Minor tweak to prevent console spam in development mode. 

### Improvements

> Added options.debug test prior to logger.debug. Otherwise, irrespective of options.debug, your console gets easily flooded.

2021-03-19 14:05 UTC, ccoeurderoy requested changes
Hi @samuelsweet!

Thank you for your contribution! Looks like the `npm run lint` command did not succeed, could please apply changes required by ESLint?

2021-03-23 08:47 UTC, ccoeurderoy commented
Thanks again @samuelsweet! Can I please ask you to amend your commit in order to respect the [angular conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) 🙂?

I will add a "Contributing" section in the README file

2021-03-23 14:11 UTC, samuelsweet commented
Hopefully thats what you're after and hopefully it helps. The log spam makes it really hard to filter through

2021-03-23 14:13 UTC, ccoeurderoy approved these changes

2021-03-23 14:13 UTC, merged